services:
  dev-db:
    image: postgres:17
    container_name: dev-container
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - freecodecamp
    volumes:
      - dev-data:/var/lib/postgresql/data
  test-db:
    image: postgres:17
    container_name: test-container
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest_db
    networks:
      - freecodecamp
    volumes:
      - test-data:/var/lib/postgresql/data

networks:
  freecodecamp:

volumes:
  dev-data:
  test-data:
